zsh:
    directories:
        - .zsh
    files:
        - .zshrc
    substitutions:
        .zshrc:
            LS COLOR PARAMETER: 
                osx: "-G"
                ubuntu: "--color"
                fedora: "--color"
            USER COLOR:
                osx:    light_red
                ubuntu: red
                fedora: red
            HOST COLOR:
                osx:    light_yellow
                ubuntu: yellow
                fedora: yellow
            PATH COLOR:
                osx:    light_green
                ubuntu: magenta
                fedora: magenta
vim:
    directories:
        - .vim session backup
        - .vim session undo
        - .vim session view
        - .vim session swp
    files:
        - .vimrc
screen:
    directories:
        - .screen
    files:
        - .screenrc
    substitutions:
        .screenrc:
            RENDITION:
                osx: sorendition 04 Kd
                ubuntu: rendition so 04 Kd
                fedora: rendition so 04 Kd
            FOCUS:
                osx: ""
                ubuntu: bind h focus left\nbind l focus right
                fedora: bind h focus left\nbind l focus right
git:
    files:    
        - .gitconfig
        - .gitignore
fonts:
    directories:
        - .fonts
    files:
        - .fonts ProggySquareSZ.ttf
